"""Phase 12: replay verifier -- VERIFIED on a clean set, TAMPERED on each edit.

The sample artifact set is generated by our own Phase 4/11 code (a test
fixture, not fabricated evidence of a real match), then each major field is
altered one at a time. Independent implementation (no import of the Police
repository's equivalent test).
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from thief_peer.domain.captures import SubGameResult
from thief_peer.domain.sealing import (
    AuditOutcome,
    AuditReport,
    SealedRecord,
    SealedTurnPayload,
    seal,
)
from thief_peer.services.artifact_builders import build_log_artifact, build_result_artifact
from thief_peer.services.artifact_models import ConfigArtifact
from thief_peer.services.artifacts import (
    config_filename,
    load_json,
    log_filename,
    result_filename,
    save_artifact,
)
from thief_peer.services.replay_verifier import verify_replay
from thief_peer.services.series_runtime import SeriesResult, SeriesSubGameRecord
from thief_peer.shared.canonical_json import canonical_json_bytes
from thief_peer.shared.config_loader import sha256_hex

CONFIG_DIR = Path(__file__).resolve().parents[2] / "config" / "thief"
UID = "abcabcab-1111-2222-3333-444444444444"
GID = "edward-donia"
N_GAMES = 3


def _terms() -> dict:
    with open(CONFIG_DIR / "game.json", encoding="utf-8") as handle:
        return json.load(handle)


def _payload(sub_game: int, step: int) -> SealedTurnPayload:
    return SealedTurnPayload(
        step=step,
        role="thief",
        sub_game_number=sub_game,
        state=f"pos={step % 7},0;visited={step + 1}",
        move="N",
        barrier_placed=None,
        capture_claim=(step % 7, 0),
        claim_response=True,
        win_claim=False,
        intent="truth",
        hint="north looks fine",
        scent_digest="d" * 64,
        scent_grid=((0.0, 0.0), (0.0, 0.0)),
        timestamp="2026-07-18T00:00:00+00:00",
        nonce=f"{sub_game:032x}{step:032x}",
        config_sha256=sha256_hex(CONFIG_DIR / "game.json"),
    )


def _write_bundle(directory: Path) -> None:
    terms = _terms()
    config_sha = sha256_hex(CONFIG_DIR / "game.json")
    for n in range(1, N_GAMES + 1):
        recs = tuple(seal(_payload(n, s)) for s in range(2))
        art = ConfigArtifact(UID, GID, n, config_sha, terms)
        save_artifact(art, directory / config_filename(GID, n))
        log = build_log_artifact(
            UID, GID, n, recs, AuditReport(AuditOutcome.VERIFIED, (), (), "ok")
        )
        save_artifact(log, directory / log_filename(GID, n))
    sub_records = tuple(
        SeriesSubGameRecord(n, SubGameResult.CAPTURE, 20, 5, 2, True) for n in range(1, N_GAMES + 1)
    )
    series = SeriesResult(sub_records, 20 * N_GAMES, 5 * N_GAMES, "completed", None)
    result = build_result_artifact(UID, GID, "deadbeef", GID, config_sha, series)
    save_artifact(result, directory / result_filename(GID))
    decl = {"schema_version": "declaration/1", "game_uid": UID, "game_id": GID, "role": "thief"}
    (directory / f"declaration_{GID}.json").write_bytes(canonical_json_bytes(decl) + b"\n")


def _tamper(tmp_path: Path, filename: str, mutate) -> None:
    path = tmp_path / filename
    data = load_json(path)
    mutate(data)
    path.write_bytes(canonical_json_bytes(data) + b"\n")


def test_clean_bundle_is_verified(tmp_path) -> None:
    _write_bundle(tmp_path)
    report = verify_replay(tmp_path)
    assert report.ok is True, report.findings
    assert report.verdict == "VERIFIED"


@pytest.mark.parametrize(
    "filename,mutate,label",
    [
        (result_filename(GID), lambda d: d.__setitem__("game_uid", "different"), "game_uid"),
        (log_filename(GID, 1), lambda d: d["steps"][0].__setitem__("move", "S"), "action"),
        (
            log_filename(GID, 1),
            lambda d: d["steps"][0].__setitem__("hint", "tampered hint"),
            "hint",
        ),
        (
            log_filename(GID, 1),
            lambda d: d["steps"][0].__setitem__("commit_hash", "0" * 64),
            "commitment",
        ),
        (log_filename(GID, 1), lambda d: d["steps"][0].__setitem__("nonce", "f" * 64), "nonce"),
        (log_filename(GID, 1), lambda d: d["steps"][0].__setitem__("step", 5), "step number"),
        (
            log_filename(GID, 1),
            lambda d: d.__setitem__("steps", d["steps"][::-1]),
            "record ordering",
        ),
        (
            log_filename(GID, 2),
            lambda d: d["steps"][0].__setitem__("barrier_placed", [99, 99]),
            "barrier declaration",
        ),
        (
            log_filename(GID, 2),
            lambda d: d["steps"][0].__setitem__("claim_response", False),
            "capture response",
        ),
        (
            config_filename(GID, 1),
            lambda d: d.__setitem__("config_sha256", "1" * 64),
            "config hash",
        ),
        (
            result_filename(GID),
            lambda d: d["sub_games"][0].__setitem__("thief_score", 999),
            "result total",
        ),
    ],
)
def test_each_tamper_is_detected(tmp_path, filename, mutate, label) -> None:
    _write_bundle(tmp_path)
    _tamper(tmp_path, filename, mutate)
    report = verify_replay(tmp_path)
    assert report.ok is False, f"{label} tamper not detected"
    assert report.verdict == "TAMPERED"
    assert report.findings


def test_missing_log_reported(tmp_path) -> None:
    _write_bundle(tmp_path)
    (tmp_path / log_filename(GID, 2)).unlink()
    report = verify_replay(tmp_path)
    assert report.ok is False
    assert report.verdict == "TAMPERED"


def test_missing_artifacts_reported(tmp_path) -> None:
    report = verify_replay(tmp_path)  # empty dir
    assert report.ok is False
    assert "missing required artifacts" in report.findings[0]


def test_duplicate_sub_game_number_is_detected(tmp_path) -> None:
    _write_bundle(tmp_path)
    _tamper(tmp_path, log_filename(GID, 2), lambda d: d.__setitem__("sub_game_number", 1))
    report = verify_replay(tmp_path)
    assert report.ok is False
    assert any("duplicate sub_game_number" in f for f in report.findings)


def test_sealed_record_helper_still_valid() -> None:
    record = seal(_payload(1, 0))
    assert isinstance(record, SealedRecord)
    assert record.recompute_matches()
